name: Build and Deploy Hugo

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.124.1'

    - name: Build site
      run: hugo --minify

    - name: Deploy with rsync
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: public/
        remote_path: ${{ secrets.SERVER_DEPLOY_PATH }}
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_port: ${{ secrets.SERVER_PORT }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}

